name: 🧪 Test
on:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 19  }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 18  }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 17  }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 16  }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 15  }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 14  }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 13  }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 12  }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 11  }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 10  }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 9.6 }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 9.5 }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 9.4 }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 9.3 }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 9.2 }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 19  }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 18  }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 17  }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 16  }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 15  }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 14  }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 13  }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 12  }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 11  }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 10  }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 9.6 }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 9.5 }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 9.4 }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 9.3 }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 9.2 }
          - { img: 🍎, os: macOS,  vm: latest,    arch: arm64,  pg: 18  }
          - { img: 🍎, os: macOS,  vm: latest,    arch: arm64,  pg: 17  }
          - { img: 🍎, os: macOS,  vm: latest,    arch: arm64,  pg: 16  }
          - { img: 🍎, os: macOS,  vm: latest,    arch: arm64,  pg: 15  }
          - { img: 🍎, os: macOS,  vm: latest,    arch: arm64,  pg: 14  }
          - { img: 🍎, os: macOS,  vm: 26-intel,  arch: amd64,  pg: 18  }
          - { img: 🍎, os: macOS,  vm: 26-intel,  arch: amd64,  pg: 17  }
          - { img: 🍎, os: macOS,  vm: 26-intel,  arch: amd64,  pg: 16  }
          - { img: 🍎, os: macOS,  vm: 26-intel,  arch: amd64,  pg: 15  }
          - { img: 🍎, os: macOS,  vm: 26-intel,  arch: amd64,  pg: 14  }
    name: ${{ matrix.img }} ${{ matrix.arch }} 🐘 ${{ matrix.pg }}
    runs-on: ${{ matrix.os }}-${{ matrix.vm }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7
      - name: Start Postgres ${{ matrix.pg }}
        id: pg
        uses: ./
        with:
          version: ${{ matrix.pg }}
          packages: libkrb5-dev libipc-run-perl
      - name: Build
        working-directory: test/pgxs
        run: make -j $(nproc)
      - name: Install
        working-directory: test/pgxs
        run: sudo make install
      - name: Test
        id: test
        working-directory: test/pgxs
        run: make installcheck
      - name: Show Diffs
        if: failure() && steps.test.outcome == 'failure'
        run: find . -name regression.diffs -exec cat {} +
      - name: Upload Diffs
        if: failure() && steps.test.outcome == 'failure'
        uses: actions/upload-artifact@v7
        with:
          name: regression-diffs-${{ matrix.os }}-${{ matrix.arch }}-pg${{ matrix.pg }}
          path: test/pgxs/regression.diffs
