name: 🧪 Test
on:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 19  }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 18  }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 17  }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 16  }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 15  }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 14  }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 13  }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 12  }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 11  }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 10  }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 9.6 }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 9.5 }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 9.4 }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 9.3 }
          - { img: 🐧, os: Ubuntu, vm: latest,    arch: amd64, pg: 9.2 }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 19  }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 18  }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 17  }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 16  }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 15  }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 14  }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 13  }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 12  }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 11  }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 10  }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 9.6 }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 9.5 }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 9.4 }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 9.3 }
          - { img: 🐧, os: Ubuntu, vm: 26.04-arm, arch: arm64, pg: 9.2 }
          - { img: 🍎, os: macOS,  vm: latest,    arch: arm64,  pg: 18  }
          - { img: 🍎, os: macOS,  vm: latest,    arch: arm64,  pg: 17  }
          - { img: 🍎, os: macOS,  vm: latest,    arch: arm64,  pg: 16  }
          - { img: 🍎, os: macOS,  vm: latest,    arch: arm64,  pg: 15  }
          - { img: 🍎, os: macOS,  vm: latest,    arch: arm64,  pg: 14  }
          - { img: 🍎, os: macOS,  vm: 26-intel,  arch: amd64,  pg: 18  }
          - { img: 🍎, os: macOS,  vm: 26-intel,  arch: amd64,  pg: 17  }
          - { img: 🍎, os: macOS,  vm: 26-intel,  arch: amd64,  pg: 16  }
          - { img: 🍎, os: macOS,  vm: 26-intel,  arch: amd64,  pg: 15  }
          - { img: 🍎, os: macOS,  vm: 26-intel,  arch: amd64,  pg: 14  }
    name: ${{ matrix.img }} ${{ matrix.arch }} 🐘 ${{ matrix.pg }}
    runs-on: ${{ matrix.os }}-${{ matrix.vm }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7
      - name: Start Postgres ${{ matrix.pg }}
        id: pg
        uses: ./
        with: { version: "${{ matrix.pg }}" }
      - name: Build
        working-directory: test/pgxs
        run: make -j $(nproc)
      - name: Install
        working-directory: test/pgxs
        run: sudo make install
      - name: Test
        id: test
        working-directory: test/pgxs
        run: make installcheck
      - name: Show Diffs
        if: failure() && steps.test.outcome == 'failure'
        run: find . -name regression.diffs -exec cat {} +
      - name: Upload Diffs
        if: failure() && steps.test.outcome == 'failure'
        uses: actions/upload-artifact@v7
        with:
          name: regression-diffs-${{ matrix.os }}-${{ matrix.arch }}-pg${{ matrix.pg }}
          path: test/pgxs/regression.diffs

  inputs:
    strategy:
      fail-fast: false
      matrix:
        pg: [18]
        os:
          - { img: 🍎, name: macOS  }
          - { img: 🐧, name: Ubuntu }
        opt:
          - { port: 6543, encoding: SQL_ASCII, locale: en_US.UTF-8 }
          - { port: 7743, encoding: EUC_KR,    locale: C,  }
    name: ${{ matrix.os.img }} ${{ matrix.os.name }} ${{ matrix.opt.encoding }}
    runs-on: ${{ matrix.os.name }}-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7
      - name: Start Postgres ${{ matrix.pg }}
        id: pg
        uses: ./
        with:
          version: ${{ matrix.pg }}
          packages: hugo
          port: ${{ matrix.opt.port }}
          encoding: ${{ matrix.opt.encoding }}
          locale: ${{ matrix.opt.locale }}
      - name: Check stuff
        run: |
          set -e
          psql -c "SELECT regexp_replace(version(), ',.+', '') AS version,
                          (SELECT setting FROM pg_catalog.pg_settings WHERE name = 'port') AS port,
                          current_setting('server_encoding') AS encoding,
                          (SELECT datcollate FROM pg_database WHERE datname = current_database()) AS locale"
          # Fail if values wrong.
          set -x
          psql -c "SELECT version()" | grep 'PostgreSQL ${{ matrix.pg }}'
          psql -c "SELECT setting FROM pg_catalog.pg_settings WHERE name = 'port'" | grep '${{ matrix.opt.port }}'
          psql -c "SELECT current_setting('server_encoding')" | grep '${{ matrix.opt.encoding }}'
          psql -c "SELECT datcollate FROM pg_database WHERE datname = current_database()" | grep '${{ matrix.opt.locale }}'
          pgxn --version # Always installed
          hugo version # Added by packages
